server:
  port: 0

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
      auto-index-creation: true
      uri: mongodb://localhost:27017/test
  mongodb:
    embedded:
      version: 5.0.0
